import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import ThemeRegistry from "../theme/ThemeRegistry";



const poppins = Poppins({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"],
});



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html lang="en" className={poppins.className}>
      <body><ThemeRegistry>{children}</ThemeRegistry></body>
    </html>
  );
}
